const val KOTLIN_VERSION = "1.6.10"
const val JBCOMPOSE_VERSION = "1.1.1"
const val KTOR_VERSION = "2.0.0-beta-1"
const val COROUTINES_VERSION = "1.6.0"
const val DOKKA_VERSION = "1.6.0"
const val BCV_VERSION = "0.8.0"
