name: Jvm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  jvm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/actions/setup-gradle@v4
      - name: Cache Build files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}
      - name: Run JVM Tests
        run: ./gradlew jvmTest checkLegacyApi
