name: Publish

on:
  push:
    tags: [ 'v*' ]
    branches: [ main ]

env:
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gradle:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: gradle/actions/setup-gradle@v4
      - name: Cache Build files
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}

      - name: Publish
        run: ./gradlew clean publishAllPublicationsToMavenCentralRepository

      - name: Build docs
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: ./gradlew clean dokkaGeneratePublicationHtml

      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          folder: build/dokka/html
          single-commit: true
